name: Build

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Build
    strategy:
      matrix:
        GOOS: [darwin, linux, openbsd, windows]
        GOARCH: [amd64, arm64]
        include:
          - GOOS: darwin
            output: converter
          - GOOS: linux
            output: converter
          - GOOS: openbsd
            output: converter
          - GOOS: windows
            output: converter.exe
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
         go-version-file: converter/go.mod
         cache: true
         cache-dependency-path: converter/go.sum

      - name: Set up workspace
        run: go work init ./converter

      - name: Build converter
        run: |
          export GOOS=${{ matrix.GOOS }}
          export GOARCH=${{ matrix.GOARCH }}
          go build -ldflags "-s -w" -o ./build/${{ matrix.output }} github.com/NovelCraft/MinecraftLevelExporter

      - name: Upload build
        uses: actions/upload-artifact@v3
        with:
          name: converter-${{ matrix.GOOS }}-${{ matrix.GOARCH }}
          path: build